### ISSUE TITLE
Use CSGOClient to login and receive error msg 9194

### ISSUE THREAD

**Issue by OraCheung** [ValvePython/csgo#13]
Hi, 
     I use CSGOClient to login,then I got a error log like it:
`       lib/python2.7/site-packages/csgo/client.py/[line:97] Failed to parse: 9194`
     I think msg 9194 mean:
`     EMsgGCCStrike15_v2_ClientGCRankUpdate = 9194`

**Comment by rossengeorgiev** [comment]
Hi, sorry for the late response. I don't see 9194 in the protobufs, might be that they are stale. I will look into it.

**Comment by rossengeorgiev** [comment]
Resolved in `v0.3.9`
