### ISSUE TITLE
When getting profile error occurs

### ISSUE THREAD

**Issue by JuniorJPDJ** [ValvePython/csgo#20]
I don't really know where it comes from, but it seems to be reproducable.
```
Unable to find key for 2
Unable to find key for 40
Unsupported type: 41
```
I could provide example credentials which generates this.
It seems to be connected with new Operation update.

**Comment by rossengeorgiev** [comment]
Just a debug log would be enough. Do you see these print out once per login per number (e.g. 2, 40, etc)?

**Comment by JuniorJPDJ** [comment]
Thank you very much for patch ;)
I've not seen your message, I'm sorry.
