### ISSUE TITLE
How to use WeeklyXPBoostReceived?

### ISSUE THREAD

**Issue by pyhtonlovertytt** [ValvePython/csgo#22]
https://github.com/ValvePython/csgo/blob/master/csgo/common_enums.py. how can I use 

class EXPFlag(IntEnum):
    UNKNOWN1                     = 0b0000000000000000000000000000001
    LevelUpDropReceived          = 0b0000000000000000000000000000010
    UNKNOWN2                     = 0b0000000000000000000000000010000  # OW or Prime status
    OverwatchXPReward            = 0b0010000000000000000000000000000
    WeeklyXPBoostReceived        = 0b0100000000000000000000000000000
    UNKNOWN3                     = 0b1000000000000000000000000000000  # OW related?

the above class for cs.account_id. Can u show an implementation to get WeeklyXPBoostReceived or not, how to check?

**Comment by rossengeorgiev** [comment]
These could be outdated, but they are only used to check against the XPFlag. If the account has weekly boost xp, the flag would be set.

**Comment by pyhtonlovertytt** [comment]
could you give a small implementation because I am able to get the data of the following:
                cs.request_player_profile(cs.account_id, request_level=32)
                PlayerProfiledata = cs.wait_event('player_profile')
                #        print("" + str(df.at[n, 'User_Name']) + ":" + str(df.at[n, 'Pass_Word']) + "")
                PlayerProfiledata[0].ranking.rank_id
                ranks_map = {0: 'Unranked', 1: 'Silver I', 2: 'Silver II', 3: 'Silver III', 4: 'Silver IV',
                             5: 'Silver Elite',
                             6: 'Silver Elite Master', 7: 'Gold Nova I', 8: 'Gold Nova II', 9: 'Gold Nova III',
                             10: 'Gold Nova Master',
                             11: 'Master Guardian I', 12: 'Master Guardian II', 13: 'Master Guardian Elite',
                             14: 'Distinguished Master Guardian', 15: 'Legendary Eagle', 16: 'Legendary Eagle Master',
                             17: 'Supreme Master First Class', 18: 'The Global Elite'}

                levels_map = {0: 'Not Recruited', 1: 'Recruit', 2: 'Private', 3: 'Private', 4: 'Private', 5: 'Corporal',
                              6: 'Corporal',
                              7: 'Corporal', 8: 'Corporal', 9: 'Sergeant', 10: 'Sergeant', 11: 'Sergeant',
                              12: 'Sergeant',
                              13: 'Master Sergeant', 14: 'Master Sergeant', 15: 'Master Sergeant',
                              16: 'Master Sergeant',
                              17: 'Sergeant Major', 18: 'Sergeant Major', 19: 'Sergeant Major', 20: 'Sergeant Major',
                              21: 'Lieutenant',
                              22: 'Lieutenant', 23: 'Lieutenant', 24: 'Lieutenant', 25: 'Captain', 26: 'Captain',
                              27: 'Captain',
                              28: 'Captain', 29: 'Major', 30: 'Major', 31: 'Major', 32: 'Major', 33: 'Colonel',
                              34: 'Colonel',
                              35: 'Colonel', 36: 'Brigadier General', 37: 'Major General', 38: 'Lieutenant General',
                              39: 'General',
                              40: 'Global General'}
                ranks_map[PlayerProfiledata[0].ranking.rank_id]

but 
EXPBonusFlag.BonusBoostConsumed.value or any other flags of class EXPBonuFlag always return their bitshift values.

**Comment by pyhtonlovertytt** [comment]
?

**Comment by pyhtonlovertytt** [comment]
it doesn't matter what account you use. You will always get class EXPBonuFlag's bitshift value. Could you give example code on, how to achieve this?
