### ISSUE TITLE
I can not get "cs.wait_event('item_data_block', 1)"

### ISSUE THREAD

**Issue by vindiesel10** [ValvePython/csgo#24]
I tried many ways to get "cs.wait_event('item_data_block', 1)" but I don't know.

My code: 
client = SteamClient()
client.cli_login('***', '***')

cs = CSGOClient(client)
cs.launch()

cs.request_preview_data_block(s=76561198390812765, a=11899154096, d=14908795644343063777, m=0)
response = cs.wait_event('item_data_block', 1)
print(response)

Answer:
C:\Users\Vanya\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gevent\monkey.py:776: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.contrib.pyopenssl (C:\\Users\\Vanya\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\urllib3\\contrib\\pyopenssl.py)']. 
  _queue_warning(

None

Help me pls.

**Comment by vindiesel10** [comment]
?

**Comment by rossengeorgiev** [comment]
Hi, you've set the timeout on your `wait_event` to only 1 second, which may not be enough. For the warning see https://github.com/ValvePython/steam/issues/97

**Comment by vindiesel10** [comment]
Thank you, I get answer.

How can I get a skin float?

My answer: 

itemid: 18130728867
defindex: 3
paintindex: 44
rarity: 4
quality: 4
paintwear: 1032788165
paintseed: 820
inventory: 3221225482
origin: 8

I see only paintwear, but it isn't float.

**Comment by rossengeorgiev** [comment]
`painwear` is the float, just needs to be converted.

```python
import struct
painfloat = struct.unpack('<f', struct.pack('<I', painwear))
```

**Comment by vindiesel10** [comment]
Thank you again.

Do you know how I can get parametrs: ''a, m, d'' for function ''request_preview_data_block''.
I use json request like this: ''https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Neon%20Revolution%20%28Field-Tested%29/render?start=0&count=100&currency=1&format=json'' but sometimes i get http status code 429. Do you know another methods for getting ''rungame url'' or parametrs ''a, m, d''?
