### ISSUE TITLE
Is it safe?

### ISSUE THREAD

**Issue by olehsamoilenko** [ValvePython/csgo#26]
Hello @rossengeorgiev 
I am actively using your package, mostly for checking float of the guns.
And I am interested how safety it is.
For example, I have single account and make ~30 requests per minute.
May steam regard that it's malicious activity or something similar?
May I be banned and how can I protect myself?
Thank you

**Comment by rossengeorgiev** [comment]
I'm not aware of anyone ever being banned. If you are setting to many request, you may get rate limited and steam will stop responding for a while.
