### ISSUE TITLE
Getting EMsg.ClientRichPresenceInfo in an event

### ISSUE THREAD

**Issue by schoerg** [ValvePython/csgo#3]
Hi, I am trying to get the `EMsg.ClientRichPresenceInfo`. However I think this info is sent out without sending something else prior. 

A function with 

```
@cs.on('EMsg.ClientRichPresenceInfo')
def test(p)
    print(p)

```
does not seem to work. Can someone point me in the right direction?

**Comment by rossengeorgiev** [comment]
You are using quotes. What you should be doing is:

```
from steam.enums.emsg import EMsg

@cs.on(EMsg.ClientRichPresenceInfo)
def test(p)
    print(p)

**Comment by schoerg** [comment]
Thank you. I tried adding it:

```
@cs.on(EMsg.ClientRichPresenceInfo)
def test(p):
	print(p)

@cs.on('ready')
def gc_ready():
	print("gc_ready")
	
client.cli_login("user", "passwd")
client.run_forever()

```

**Comment by rossengeorgiev** [comment]
Oh right. If look at the log you will notice that the event happens on the `SteamClient` instance, so `client` in your case, not `CSGOClient`.

**Comment by schoerg** [comment]
Thanks, that was the right hint.
