### ISSUE TITLE
How to automatically reconnect to GC?

### ISSUE THREAD

**Issue by tmick0** [ValvePython/csgo#35]
During Tuesday's routine maintenance I discovered that the client does not automatically reconnect to the GC after having been disconnected. This was not unexpected, however it is not immediate clear how to detect this event and attempt a reconnection.

My first thought was to borrow the `steam` lib's [recipe for persistent login](https://github.com/ValvePython/steam/blob/master/recipes/1.Login/persistent_login.py), with hope that including this in my project would also provide persistent connection to CS:GO (given that I call `csgo`'s `launch()` on the `steam` client's `logged_on` event).

Can someone confirm whether this is correct, or if not provide the correct approach to reconnect?

**Comment by rossengeorgiev** [comment]
Yes, you have to run `CSGOClient.launch()` to initiate session to GC after every reconnect. 

https://github.com/rossengeorgiev/pydle-irc/blob/cf0368ae87dbe30ef7eb6388fe93cdb6b22a8618/pydle-steam.py#L58-L70

**Comment by tmick0** [comment]
thank you :)
