### ISSUE TITLE
Get store items

### ISSUE THREAD

**Issue by ghost** [ValvePython/csgo#41]
How could I fetch items that can currently be bought from the in-game shop?

**Comment by rossengeorgiev** [comment]
You will have to nethook the client and figure out how it fetches that item list

**Comment by ghost** [comment]
> 
> 
> You will have to nethook the client and figure out how it fetches that item list

I did but I didn't find anythnig, can I somehow add a handler to decode all received messages?

**Comment by rossengeorgiev** [comment]
If you enable debug logging, you will see all message received and sent. Game clients also do various things over HTTP, such as interacting with various WebAPI endpoints.
