### ISSUE TITLE
ClientMicroTxnAuthorize

### ISSUE THREAD

**Issue by ghost** [ValvePython/csgo#43]
How on earth do I send steam.enums.emsg.EMsg.ClientMicroTxnAuthorize?

**Comment by ghost** [comment]
when I do csgoclient.send(steam.enums.emsg.EMsg.ClientMicroTxnAuthorize) it causes error:
ValueError: Unable to find proto for emsg, or proto kwarg is invalid

**Comment by rossengeorgiev** [comment]
Best to read the docs on how to send messages.
