### ISSUE TITLE
How can i get accound id of user?

### ISSUE THREAD

**Issue by Soulbadguy54** [ValvePython/csgo#45]
Hello, I have all info like steam_id, auth-key, share_code. When i get dict with all match_info, there are only account_id's. Who can i correspond  account_id and some other info to identify user? Probably i should use some methods?

**Comment by rossengeorgiev** [comment]
Just use `SteamID(account_id)`

**Comment by Soulbadguy54** [comment]
> Just use `SteamID(account_id)`

Thx you!
