### ISSUE TITLE
How to add csgo to new account?

### ISSUE THREAD

**Issue by SAYNEY** [ValvePython/csgo#47]
I made a simple autoreg, after creating an account, I want idle hours in csgo, but a simple cs.launch () is not enough, hours are not added. So, my question is "How to add CS:GO to steam library."

**Comment by rossengeorgiev** [comment]
I cannot provide help for anything related to the automated creation of accounts, and I would advise against doing it.

**Comment by SAYNEY** [comment]
I wanted to ask you about, how to add CS:GO to steam library using your library.
