### ISSUE TITLE
Understanding how to convert a steam id into an account id

### ISSUE THREAD

**Issue by Petinga** [ValvePython/csgo#56]
I have some Steam id from users and i am trying to get their account ids in order to get their previous matches. Is there a specific way to do this with the package, i read the documentation, and wasnt able to find any direct way to do so. Am i just missing something or is there no way to do so?

**Comment by Petinga** [comment]
Nevermind i figured all i needed was the 32 bit id i needed.

**Comment by rossengeorgiev** [comment]
Look in the docs for [SteamID](https://steam.readthedocs.io/en/latest/user_guide.html?highlight=steamid#steamid)

```python
client = SteamClient()
# after login
client.user # hosts SteamID instance of the logged in account
client.user.id # account id
