### ISSUE TITLE
Is it possible to get info about prime?

### ISSUE THREAD

**Issue by OliverTrust** [ValvePython/csgo#57]
Can't find any cs gc msg with this info

**Comment by verdammnis** [comment]
[CSOEconGameAccountClient.elevated_state](https://www.unknowncheats.me/forum/counterstrike-global-offensive/445296-info-prime-status-csgo-protobufs.html)

**Comment by rossengeorgiev** [comment]
Data is accessible on https://github.com/ValvePython/csgo/blob/ed81efa8c36122e882ffa5247be1b327dbd20850/protobufs/base_gcmessages.proto#L105-L111

See https://csgo.readthedocs.io/en/stable/csgo.features.sharedobjects.html

There is an enum to help decode the values, but its probably not up to date: https://github.com/ValvePython/csgo/blob/ed81efa8c36122e882ffa5247be1b327dbd20850/csgo/common_enums.py#L16-L25

The reversed code from previous comments mentions how to check for prime.

**Comment by OliverTrust** [comment]
Thank you for fast help
