### ISSUE TITLE
Incorrect data being returned

### ISSUE THREAD

**Issue by SaimM95** [ValvePython/csgo#6]
I used the api to get my recent game data like the following:
```
    cs.request_recent_user_games(cs.account_id)
    response = cs.wait_event('recent_user_games')
```
However, the data being returned is not correct (i.e. doesn't match the data in game). More specifically, only the account_ids seem to match the actual data. Kills, deaths, etc. all seem to be random numbers. What am I doing wrong here?

**Comment by rossengeorgiev** [comment]
Can't replicate what you describing. Prehaps you are looking at the wrong round? The last round is what you will see when you look at you recent matches in CSGO. So, for you latest match you can grab only that round with like:

```python
resp = cs.wait_event('recent_user_games')
resp.matches[0].roundstatall[-1]  # last round of last match
```

**Comment by SaimM95** [comment]
Tried this `latestGame = response.matches[0]  # last round of last match`
Got this `AttributeError: 'tuple' object has no attribute 'matches'`

**Comment by rossengeorgiev** [comment]
Oh my bad. I used `wait_event` instead of `wait_msg`.

```python
resp = cs.wait_msg('recent_user_games')
resp.matches[0].roundstatall[-1]

**Comment by SaimM95** [comment]
Okay that worked. This is the response now. How can a player get 13 kills in one round? o.O

```
  ...
  kills: 13
  kills: 8
  kills: 8
  kills: 6
  kills: 5
  kills: 10
  kills: 6
  kills: 7
  kills: 5
  kills: 3
  ...
```

**Comment by SaimM95** [comment]
Okay. I think I understand now. Thanks for quick responses :D

**Comment by rossengeorgiev** [comment]
I'm closing this as it looks resolved. Feel free to reopen
