### ISSUE TITLE
error : cannot import name 'CSGOClient' on the example program

### ISSUE THREAD

**Issue by zer0kK** [ValvePython/csgo#7]
the program here : 
http://csgo.readthedocs.io/en/stable/user_guide.html#initialization

error :
ImportError: cannot import name 'CSGOClient'

`

**Comment by rossengeorgiev** [comment]
What is the import statement that you are using? Please also include the full trace

**Comment by zer0kK** [comment]
i had an old python file named "csgo.py" that was causing the issues , i deleted it and it got fixed 
:) thanks for the help tho :+1:
