### ISSUE TITLE
After some time, EMsgGCCStrike15_v2_Client2GCEconPreviewDataBlockRequest consistently returns `None`

### ISSUE THREAD

**Issue by mattrberry** [ValvePython/csgo#9]
The code that I am having issues with can be seen [here](https://github.com/mattrberry/csgoSkinStatistics), specifically in [this file](https://github.com/mattrberry/csgoSkinStatistics/blob/master/inventory.py) on [this line](https://github.com/mattrberry/csgoSkinStatistics/blob/master/inventory.py#L32).

To reproduce the issue I am having, simply run the code I have provided, wait a few minutes without sending any requests (not sure how long specifically), then try to send a request. (Please read the readme on the repo I have linked, it explains how to run and use the code.) The script will try to call the method 3 times and receive `None` each time.

_It can be noted that I have set the `timeout` to be only 1 second, but this issue persists no matter how long I set this interval to be._

I don't think this is rate limiting. If I run the code and make a lot of calls quickly, it works for a few calls before beginning to fail *as expected* due to rate limiting. The issue I have described though can occur as early as the first call if the first call is made after waiting a few minutes.

**Comment by rossengeorgiev** [comment]
Ok, I see the problem.

https://github.com/mattrberry/csgoSkinStatistics/blob/d7104fe0a6b2db2eed5229902d2da7207562b204/inventory.py#L21

You block the gevent there, so after a few minutes the steam connection will drop due being unable to send heartbeats. You want to setup reconnection logic for `SteamClient`, kick it off, and then hand it off to flask. You also have to use gevent's WSGISever to serve flask. However, having `app.run()` will cause problems. I suggest reviewing this recipe:  https://github.com/ValvePython/steam/tree/master/recipes/2.SimpleWebAPI

**Comment by mattrberry** [comment]
Thank you so much for the quick and detailed reply, I'll take a look at in the next day or two! Thanks again for all your work on these projects!

**Comment by mattrberry** [comment]
Hey @rossengeorgiev, I'm not sure if this is the place to discuss this but I just have a quick followup question. I'm trying to create a super simple implementation resembling the recipe you suggested. Just as an example, I have added the two files "run_webapi.py" and "csgo_worker.py" to the base of the repo I mentioned before. I'm having trouble with [this line specifically](https://github.com/mattrberry/csgoSkinStatistics/blob/master/csgo_worker.py#L35). Steam fails to connect, so my program never gets past this line.

Is there something that I am blatantly doing wrong, as before? I'll keep trying to trace the issue, but I thought you might take a look at it again and see immediately where I've gone wrong. Thanks again! Your work and help is much appreciated! :)

**Comment by rossengeorgiev** [comment]
Try using calling `login()` somewhere

**Comment by mattrberry** [comment]
Awesome, that was it haha. Thank you so much!
